#!/bin/bash

if [ ! -d "$DINGOO_SDK" ]; then
	echo "DINGOO_SDK environment variable not set/valid."
	exit 0
fi

if [ ! -d "$MIPSTOOLS" ]; then
	echo "MIPSTOOLS environment variable not set/valid."
	exit 0
fi

if [ -d "$WINDIR" ]; then
	SET nodosfilewarning
	$DINGOO_SDK/tools/mipstools_fix/mipstools_fix
else
	rm -f $DINGOO_SDK/tools/elf2app/elf2app
	cc $DINGOO_SDK/tools/elf2app/src/*.c -o $DINGOO_SDK/tools/elf2app/elf2app
	rm -f $DINGOO_SDK/tools/bin2h/bin2h
	cc $DINGOO_SDK/tools/bin2h/src/bin2h.c -o $DINGOO_SDK/tools/bin2h/bin2h
fi

cd $DINGOO_SDK/src/jz4740 && make clean && make headers
cd $DINGOO_SDK/src/libc && make clean && make headers
cd $DINGOO_SDK/src/libm && make clean && make headers
cd $DINGOO_SDK/src/libstdc++ && make clean && make headers
cd $DINGOO_SDK/src/sml && make clean && make headers
cd $DINGOO_SDK/src/modplay && make clean && make headers
cd $DINGOO_SDK/src/zlib && make clean && make headers
cd $DINGOO_SDK/src/libpng && make clean && make headers
cd $DINGOO_SDK/src/freetype && make clean && make headers
cd $DINGOO_SDK/src/tremor && make clean && make headers
cd $DINGOO_SDK/src/libmikmod/dingoo && make clean && make headers
cd $DINGOO_SDK/src/SDL && make clean && make headers

cd $DINGOO_SDK/src/jz4740 && make
cd $DINGOO_SDK/src/libc && make
cd $DINGOO_SDK/src/libm && make
cd $DINGOO_SDK/src/libstdc++ && make
cd $DINGOO_SDK/src/sml && make
cd $DINGOO_SDK/src/modplay && make
cd $DINGOO_SDK/src/zlib && make
cd $DINGOO_SDK/src/libpng && make
cd $DINGOO_SDK/src/freetype && make
cd $DINGOO_SDK/src/tremor && make
cd $DINGOO_SDK/src/libmikmod/dingoo && make
cd $DINGOO_SDK/src/SDL && make

rm -f $DINGOO_SDK/lib/libgcc.a
cp $MIPSTOOLS/lib/gcc/mipsel-linux/*/libgcc.a $DINGOO_SDK/lib

rm -f $DINGOO_SDK/lib/dingoo.xn
echo "ENTRY(AppMain)
OUTPUT_FORMAT("elf32-tradlittlemips")
SECTIONS
{
    .dingoo 0x80A00000 :
    { 
        dingoo.o (.text)
        *(.text*)
        *(.rodata*)
        *(.data*)
        *(.eh_frame*)
        *(.gcc_except_table*)

        . = ALIGN(8);
        __CTOR_LIST__ = ABSOLUTE(.);
        KEEP(*(SORT(.ctors*)))
        __CTOR_END__ = ABSOLUTE(.);
        __DTOR_LIST__ = ABSOLUTE(.);
        KEEP(*(SORT(.dtors*)))
        __DTOR_END__ = ABSOLUTE(.);

        *(.lit8)
        *(.lit4)
        *(.sdata)
    }
    _fbss = .;
    .bss :
    {
        *(.sbss)
        *(.scommon)
        *(.bss*)
        *(COMMON)
    }
    _end = .;
    .export_table :
    {
        KEEP(*(.export_table))
    }
	.export_string :
    {
        KEEP(*(.export_string))
    }
    /DISCARD/ :
    {
        *(*)
    }
}
" > $DINGOO_SDK/lib/dingoo.xn

echo "Dingoo SDK installed."
